const DATA = {
    1: {section:'math', q:'If A and B are real orthogonal matrices of same order and det(A) + det(B) = 0, then A + B is',
        answer:'(A) a singular matrix',
        explanation:'Orthogonal matrices have determinant = ±1. If det(A)+det(B)=0 one is +1 and other -1, so A+B becomes singular (non-invertible).',
        hasFormula:true, formula:'det(A)=\\pm 1 for orthogonal matrices<br>A^T A = I' },
    2: {section:'math', q:'For the matrix A = \\begin{pmatrix} 1 & 0 & 3 \\\\ 4 & -1 & 5 \\\\ 2 & 0 & 6 \\end{pmatrix}, which of the following is correct?',
        answer:'(C) rank A = 2', explanation:'Row 3 = 2 × Row 1, so only 2 independent rows. Rank = 2.', hasFormula:true, formula:'Matrix rank = number of linearly independent rows' },
    3: {section:'math', q:'If A = \\begin{pmatrix} 3 & -4 \\\\ 1 & -1 \\end{pmatrix}, then A^K (where K is any positive integer) is',
        answer:'(A) \\begin{pmatrix} 1+2K & -4K \\\\ K & 1-2K \\end{pmatrix}', explanation:'Pattern check and induction on powers gives that closed form.',
        hasFormula:true, formula:'Matrix powers by induction' },
    4: {section:'math', q:'If pλ⁴ + qλ³ + rλ² + sλ + t = det(...) (given), then t =',
        answer:'(D) -33', explanation:'Constant term t found by evaluating determinant at λ=0 gives -33.',
        hasFormula:true, formula:'Determinant expansion' },
    5: {section:'math', q:'If Δ₁ = det[[x,b,b],[a,x,b],[a,a,x]] and Δ₂ = det[[x,b],[a,x]] then',
        answer:'(B) d/dx(Δ₁) = 3Δ₂', explanation:'Compute Δ₁=x^3-3abx+2a^2b^2, differentiate to get 3x^2-3ab = 3Δ₂.',
        hasFormula:true, formula:'Δ₁ = x^3 - 3abx + 2a^2b^2<br>Δ₂ = x^2 - ab' },
    6: {section:'math', q:'If determinant(...) = K a^2 b^2 c^2 then K =', answer:'(B) 4', explanation:'Expand and factor to get K=4.',
        hasFormula:true, formula:'Determinant expansion' },
    7: {section:'math', q:'If x = e^{jθ} and y = e^{jφ}, then x^m/y^n + y^n/x^m =',
        answer:'(B) 2 cos(mθ - nφ)', explanation:'Use Euler: e^{jα}+e^{-jα}=2cosα.',
        hasFormula:true, formula:'e^{iθ}=cosθ+i sinθ' },
    8: {section:'math', q:'If ratio (Z-i)/(Z-1) is purely imaginary, then Z lies on', answer:'(B) a circle', explanation:'Put Z=x+iy, force real part=0 gives circle equation.',
        hasFormula:true, formula:'Z=x+iy\\; complex algebra' },
    9: {section:'math', q:'If normal to xy = e² at (e/t1,e/t1) meets curve at (e/t2,e/t2), then', answer:'(B) t1^3 t2 = -1', explanation:'Solve normal equation — gives relation t1^3 t2 = -1.',
        hasFormula:true, formula:'xy=c^2; normal slope and algebra' },
    10:{section:'math', q:'Length of tangent from any point on circle x²+y²+2gx+2fy+c=0 to circle x²+y²+2gx+2fy+c\'=0 is', answer:'(C) (c - c\\\')^{1/2}', explanation:'Both circles same center; tangent length = sqrt(r1^2 - r2^2) which simplifies to sqrt(c-c\\\').',
        hasFormula:true, formula:'radius=\\sqrt{g^2+f^2-c}'},
    11:{section:'math', q:'If |A+B|=|A-B| then angle between A and B is', answer:'(B) π/2', explanation:'Square both sides gives A·B=0 ⇒ 90°.',
        hasFormula:true, formula:'|A+B|^2=|A|^2+|B|^2+2A·B'},
    12:{section:'math', q:'Three vectors a,b,c satisfy a+b+c=0, |a|=3,|b|=4,|c|=2. Find a·b + b·c + c·a', answer:'(B) -29/2', explanation:'(a+b+c)^2=0 ⇒ compute and solve.',
        hasFormula:true, formula:'(a+b+c)^2 = a^2+b^2+c^2+2Σa·b'},
    13:{section:'math', q:'Particle acted by forces 4i+j-3k and 3i+j-k displaced from i+2j+3k to 5i+4j+k. Work done?', answer:'(B) 40 units', explanation:'Sum forces then dot with displacement gives 40.',
        hasFormula:true, formula:'W=F·d'},
    14:{section:'math', q:'Domain of f(x)=sin^{-1} (log_2(x^2/2)) is', answer:'(C) [-√2,-1] ∪ [1,√2]', explanation:'Ensure log term in [-1,1] and domain of log; simplifies to stated intervals.',
        hasFormula:true, formula:'-1 ≤ log_2(x^2/2) ≤ 1'},
    15:{section:'math', q:'If f\\\'(a) exists then lim_{h→0}[f(a+h)-f(a-h)]/h equals', answer:'(C) 2f\\\'(a)', explanation:'Split limit into two one-sided derivatives gives 2f\\\'(a).',
        hasFormula:true, formula:'limit identity'},
    16:{section:'math', q:'Value of f(π) for continuity where f(x) = [1-cos7(x-π)]/(x-π)', answer:'(D) 0', explanation:'Use substitution t=x-π and standard limit → 0.',
        hasFormula:true, formula:'lim_{t→0}(1-cos(kt))/t = 0'},
    17:{section:'math', q:'If f is continuous on [a,b], differentiable on (a,b) and f\\\'(x)=0 for all x, then', answer:'(B) f(x)=constant', explanation:'Derivative zero ⇒ constant.',
        hasFormula:true, formula:'f\\\' = 0 ⇒ constant'},
    18:{section:'math', q:'Where f(x)=2 log_2(x-2) - x^2 +4x +1 increases?', answer:'(B) (2,3)', explanation:'Differentiate and test sign; domain x>2.',
        hasFormula:true, formula:'f\\\'(x) expression'},
    19:{section:'math', q:'Max value of xy with 3x+4y=5', answer:'(B) 25/48', explanation:'Substitute y and maximize quadratic; vertex at x=5/6.',
        hasFormula:true, formula:'xy=(5x-3x^2)/4'},
    20:{section:'math', q:'If y = sin(log x), then x²y₂ + xy₁ + y =', answer:'(D) 0', explanation:'Differentiate twice and substitute to get 0.',
        hasFormula:true, formula:'Chain rule and substitution'},
    21:{section:'math', q:'If x = a(θ - sinθ), y = a(1 - cosθ), then dy/dx at θ=π/2 is', answer:'(C) 1', explanation:'Compute dy/dθ and dx/dθ, then dy/dx = (dy/dθ)/(dx/dθ) = cot(θ/2).',
        hasFormula:true, formula:'Parametric differentiation'},
    22:{section:'math', q:'If y = (sin⁻¹x)², then (1-x²)y₂ - xy₁ =', answer:'(B) 2', explanation:'Differentiate twice and simplify.',
        hasFormula:true, formula:'Implicit differentiation'},
    23:{section:'math', q:'If x^y = e^{x-y}, then dy/dx =', answer:'(A) (log x)/((1+log x)²)', explanation:'Take log on both sides, differentiate implicitly.',
        hasFormula:true, formula:'Implicit differentiation'},
    24:{section:'math', q:'If y = (1+x)(1+x²)(1+x⁴)...(1+x²ⁿ), then dy/dx at x=0 is', answer:'(C) 1', explanation:'y = (1-x²ⁿ⁺¹)/(1-x). Differentiate and substitute x=0.',
        hasFormula:true, formula:'Geometric series product'},
    25:{section:'math', q:'∫ (sin x + cos x)/√(1 + sin 2x) dx =', answer:'(A) x + c', explanation:'Denominator is |sin x + cos x|. Integral is ∫ dx.',
        hasFormula:true, formula:'1+sin 2x = (sin x + cos x)²'},
    26:{section:'math', q:'∫ dx/(x² + 2x + 2) =', answer:'(B) tan⁻¹(x+1) + c', explanation:'Complete the square: x²+2x+2 = (x+1)²+1.',
        hasFormula:true, formula:'∫ dx/(x²+a²) = (1/a)tan⁻¹(x/a)'},
    27:{section:'math', q:'∫ (x² + 1)/(x⁴ + 1) dx =', answer:'(C) (1/√2) tan⁻¹((x - 1/x)/√2) + c', explanation:'Divide numerator and denominator by x² and substitute t = x - 1/x.',
        hasFormula:true, formula:'Substitution method'},
    28:{section:'math', q:'∫₀^{π/2} (sin x - cos x)/(1 + sin x cos x) dx =', answer:'(D) 0', explanation:'Use property ∫₀ᵃ f(x) dx = ∫₀ᵃ f(a-x) dx. The integral is equal to its negative.',
        hasFormula:true, formula:'Definite integral property'},
    29:{section:'math', q:'∫₀^{π/2} log(tan x) dx =', answer:'(A) 0', explanation:'Use property ∫₀ᵃ f(x) dx = ∫₀ᵃ f(a-x) dx. The integral is equal to its negative.',
        hasFormula:true, formula:'Definite integral property'},
    30:{section:'math', q:'Area bounded by y = x² and y = 2 - x² is', answer:'(B) 8/3', explanation:'Find intersection points x=±1. Area = ∫₋₁¹ (2-x² - x²) dx.',
        hasFormula:true, formula:'Area between curves'},
    31:{section:'math', q:'Order and degree of differential equation (d²y/dx²)³ + (dy/dx)⁴ + sin(dy/dx) + 1 = 0 are', answer:'(C) 2, not defined', explanation:'Order is 2. Degree is not defined due to sin(dy/dx).',
        hasFormula:true, formula:'Order and degree definition'},
    32:{section:'math', q:'Solution of differential equation dy/dx = e^{x-y} + x²e⁻ʸ is', answer:'(A) eʸ = eˣ + x³/3 + c', explanation:'Separate variables: eʸ dy = (eˣ + x²) dx.',
        hasFormula:true, formula:'Separation of variables'},
    33:{section:'math', q:'Solution of differential equation (x² + y²) dx = 2xy dy is', answer:'(B) x² - y² = cx', explanation:'Homogeneous equation. Substitute y=vx.',
        hasFormula:true, formula:'Homogeneous DE substitution'},
    34:{section:'math', q:'Solution of differential equation (1 + x²) dy/dx + 2xy = 4x² is', answer:'(D) y(1 + x²) = 4x³/3 + c', explanation:'Linear DE. Integrating factor is 1+x². y(IF) = ∫ Q(IF) dx.',
        hasFormula:true, formula:'Linear DE: IF = e^{∫P dx}'},
    35:{section:'math', q:'The probability that a leap year selected at random will contain 53 Sundays is', answer:'(A) 2/7', explanation:'Leap year has 366 days (52 weeks + 2 days). 2 days can be (Sun, Mon), (Mon, Tue), ..., (Sat, Sun). 2 favorable outcomes out of 7.',
        hasFormula:true, formula:'Leap year days'},
    36:{section:'math', q:'A coin is tossed 6 times. The probability of getting at least 3 heads is', answer:'(B) 42/64', explanation:'Binomial distribution. P(X≥3) = P(3)+P(4)+P(5)+P(6).',
        hasFormula:true, formula:'Binomial probability P(X=k) = C(n,k)p^k(1-p)^{n-k}'},
    37:{section:'math', q:'If P(A) = 0.5, P(B) = 0.3, P(A∩B) = 0.15, then P(A/B) is', answer:'(C) 0.5', explanation:'P(A/B) = P(A∩B) / P(B).',
        hasFormula:true, formula:'Conditional probability'},
    38:{section:'math', q:'The mean and variance of a binomial distribution are 4 and 2 respectively. The probability of getting exactly 2 successes is', answer:'(D) 28/256', explanation:'np=4, np(1-p)=2. Solve for n and p. P(X=2) = C(8,2)(1/2)²(1/2)⁶.',
        hasFormula:true, formula:'Binomial mean and variance'},
    39:{section:'math', q:'If a random variable X follows Poisson distribution such that P(X=1) = P(X=2), then P(X=0) is', answer:'(A) e⁻²', explanation:'P(X=k) = e⁻λ λᵏ/k!. Solve for λ=2. P(X=0) = e⁻².',
        hasFormula:true, formula:'Poisson probability'},
    40:{section:'math', q:'If the mean of a normal distribution is 100 and standard deviation is 10, then the coefficient of variation is', answer:'(B) 10%', explanation:'CV = (SD/Mean) × 100%.',
        hasFormula:true, formula:'Coefficient of variation'},
    41:{section:'physics', q:'A body is projected vertically upwards with a velocity of 98 m/s. The time taken to reach the maximum height is', answer:'(A) 10 s', explanation:'v = u - gt. At max height, v=0. t = u/g = 98/9.8 = 10 s.',
        hasFormula:true, formula:'v = u - gt'},
    42:{section:'physics', q:'A particle moves in a straight line such that its displacement x at time t is given by x = t³ - 6t² + 3t + 4. The velocity when acceleration is zero is', answer:'(C) -9 m/s', explanation:'v = dx/dt = 3t² - 12t + 3. a = dv/dt = 6t - 12. a=0 ⇒ t=2. v(2) = 3(4) - 12(2) + 3 = -9.',
        hasFormula:true, formula:'v=dx/dt, a=dv/dt'},
    43:{section:'physics', q:'A body of mass 5 kg is moving with a velocity of 10 m/s. The momentum of the body is', answer:'(B) 50 kg m/s', explanation:'Momentum p = mv.',
        hasFormula:true, formula:'p = mv'},
    44:{section:'physics', q:'A force of 10 N acts on a body of mass 2 kg for 5 s. The change in momentum is', answer:'(D) 50 kg m/s', explanation:'Impulse = Change in momentum = F × t.',
        hasFormula:true, formula:'Impulse = FΔt'},
    45:{section:'physics', q:'The angular velocity of a particle moving in a circle of radius 5 m with a linear velocity of 10 m/s is', answer:'(A) 2 rad/s', explanation:'v = rω. ω = v/r = 10/5 = 2 rad/s.',
        hasFormula:true, formula:'v = rω'},
    46:{section:'physics', q:'The moment of inertia of a disc of mass M and radius R about an axis passing through its center and perpendicular to its plane is', answer:'(C) MR²/2', explanation:'Standard formula.',
        hasFormula:true, formula:'I = MR²/2'},
    47:{section:'physics', q:'The escape velocity from the surface of the Earth is approximately', answer:'(B) 11.2 km/s', explanation:'Standard value.',
        hasFormula:false, formula:''},
    48:{section:'physics', q:'The work done in moving a charge of 5 C from a point at 10 V to a point at 50 V is', answer:'(D) 200 J', explanation:'W = qΔV = 5 × (50 - 10) = 200 J.',
        hasFormula:true, formula:'W = qΔV'},
    49:{section:'physics', q:'The equivalent resistance of two resistors 10 Ω and 20 Ω connected in parallel is', answer:'(A) 20/3 Ω', explanation:'1/R_eq = 1/R₁ + 1/R₂.',
        hasFormula:true, formula:'1/R_eq = 1/R₁ + 1/R₂'},
    50:{section:'physics', q:'The power of a lens is +2.0 D. The focal length is', answer:'(C) 50 cm', explanation:'P = 1/f (in meters). f = 1/2.0 m = 0.5 m = 50 cm.',
        hasFormula:true, formula:'P = 1/f'},
    51:{section:'physics', q:'The minimum distance between an object and its real image formed by a convex lens is', answer:'(B) 4f', explanation:'When u=2f, v=2f, distance is 4f. For real image, u and v must be positive, and the minimum distance is 4f.',
        hasFormula:true, formula:'Lens formula'},
    52:{section:'physics', q:'The ratio of the speed of light in vacuum to the speed of light in a medium is called', answer:'(A) Refractive index', explanation:'Definition of refractive index.',
        hasFormula:true, formula:'n = c/v'},
    53:{section:'physics', q:'The phenomenon of light responsible for the blue color of the sky is', answer:'(C) Scattering', explanation:'Rayleigh scattering.',
        hasFormula:false, formula:''},
    54:{section:'physics', q:'The energy of a photon with wavelength 600 nm is (h = 6.63 × 10⁻³⁴ J s, c = 3 × 10⁸ m/s)', answer:'(D) 3.315 × 10⁻¹⁹ J', explanation:'E = hc/λ.',
        hasFormula:true, formula:'E = hc/λ'},
    55:{section:'physics', q:'The half-life of a radioactive substance is 10 days. The time taken for 75% of the substance to decay is', answer:'(B) 20 days', explanation:'75% decay means 25% remains (1/4). (1/2)² = 1/4. Time = 2 × half-life.',
        hasFormula:true, formula:'N = N₀(1/2)ⁿ'},
    56:{section:'physics', q:'The unit of magnetic flux is', answer:'(A) Weber', explanation:'Standard unit.',
        hasFormula:false, formula:''},
    57:{section:'physics', q:'The self-inductance of a coil is 5 H. The current changes from 10 A to 5 A in 0.1 s. The induced EMF is', answer:'(C) 250 V', explanation:'|EMF| = L |dI/dt| = 5 × |(5-10)/0.1| = 250 V.',
        hasFormula:true, formula:'EMF = -L dI/dt'},
    58:{section:'physics', q:'The RMS value of an AC current is 10 A. The peak value is', answer:'(B) 10√2 A', explanation:'I_rms = I_peak / √2.',
        hasFormula:true, formula:'I_{rms} = I_{peak}/\\sqrt{2}'},
    59:{section:'physics', q:'The ratio of the velocity of sound in air to the velocity of sound in water is', answer:'(D) Less than 1', explanation:'Sound travels faster in water than in air.',
        hasFormula:false, formula:''},
    60:{section:'physics', q:'The fundamental frequency of an open organ pipe is 100 Hz. The frequency of the first overtone is', answer:'(A) 200 Hz', explanation:'Frequencies are f, 2f, 3f, ... First overtone is 2f.',
        hasFormula:true, formula:'Open pipe frequencies'},
    61:{section:'chemistry', q:'The number of moles of solute in 1 kg of solvent is called', answer:'(B) Molality', explanation:'Definition of molality.',
        hasFormula:false, formula:''},
    62:{section:'chemistry', q:'The pH of a 0.01 M HCl solution is', answer:'(C) 2', explanation:'HCl is a strong acid. [H⁺] = 0.01 M = 10⁻² M. pH = -log[H⁺] = 2.',
        hasFormula:true, formula:'pH = -log[H⁺]'},
    63:{section:'chemistry', q:'The oxidation number of Mn in KMnO₄ is', answer:'(D) +7', explanation:'K(+1) + Mn(x) + 4×O(-2) = 0. x = +7.',
        hasFormula:true, formula:'Oxidation number calculation'},
    64:{section:'chemistry', q:'The unit of rate constant for a first-order reaction is', answer:'(A) s⁻¹', explanation:'Standard unit.',
        hasFormula:false, formula:''},
    65:{section:'chemistry', q:'The half-life period of a first-order reaction is 60 minutes. The time required for 90% completion of the reaction is', answer:'(B) 199.3 minutes', explanation:'k = 0.693/t₁/₂. t = (2.303/k) log(100/10).',
        hasFormula:true, formula:'First-order kinetics'},
    66:{section:'chemistry', q:'The process of converting vegetable oil into solid fat is called', answer:'(C) Hydrogenation', explanation:'Addition of hydrogen in the presence of a catalyst.',
        hasFormula:false, formula:''},
    67:{section:'chemistry', q:'The monomer of natural rubber is', answer:'(A) Isoprene', explanation:'Standard fact.',
        hasFormula:false, formula:''},
    68:{section:'chemistry', q:'The general formula of an alkane is', answer:'(D) CₙH₂ₙ₊₂', explanation:'Standard formula.',
        hasFormula:false, formula:''},
    69:{section:'chemistry', q:'The IUPAC name of CH₃CH₂COCH₃ is', answer:'(B) Butanone', explanation:'4 carbons, ketone group at position 2.',
        hasFormula:false, formula:''},
    70:{section:'chemistry', q:'The functional group of an alcohol is', answer:'(C) -OH', explanation:'Standard functional group.',
        hasFormula:false, formula:''},
    71:{section:'chemistry', q:'The most electronegative element is', answer:'(A) Fluorine', explanation:'Standard fact.',
        hasFormula:false, formula:''},
    72:{section:'chemistry', q:'The number of electrons in the outermost shell of an element with atomic number 17 is', answer:'(D) 7', explanation:'Electronic configuration: 2, 8, 7 (Chlorine).',
        hasFormula:false, formula:''},
    73:{section:'chemistry', q:'The shape of a methane molecule (CH₄) is', answer:'(B) Tetrahedral', explanation:'sp³ hybridization.',
        hasFormula:false, formula:''},
    74:{section:'chemistry', q:'The bond order of N₂ molecule is', answer:'(C) 3', explanation:'Triple bond.',
        hasFormula:false, formula:''},
    75:{section:'chemistry', q:'The gas used in fire extinguishers is', answer:'(A) CO₂', explanation:'Standard fact.',
        hasFormula:false, formula:''},
    76:{section:'electrical', q:'The unit of electric charge is', answer:'(B) Coulomb', explanation:'Standard unit.',
        hasFormula:false, formula:''},
    77:{section:'electrical', q:'Ohm\\\'s law is applicable to', answer:'(C) Metallic conductors', explanation:'Ohmic materials.',
        hasFormula:false, formula:''},
    78:{section:'electrical', q:'The reciprocal of resistance is', answer:'(A) Conductance', explanation:'G = 1/R.',
        hasFormula:true, formula:'G = 1/R'},
    79:{section:'electrical', q:'The power consumed in a circuit with voltage V and current I is', answer:'(D) P = VI', explanation:'Standard formula.',
        hasFormula:true, formula:'P = VI'},
    80:{section:'electrical', q:'The total capacitance of two capacitors C₁ and C₂ connected in series is', answer:'(B) (C₁C₂)/(C₁ + C₂)', explanation:'1/C_eq = 1/C₁ + 1/C₂.',
        hasFormula:true, formula:'1/C_{eq} = 1/C₁ + 1/C₂'},
    81:{section:'electrical', q:'The energy stored in a capacitor with capacitance C and voltage V is', answer:'(C) ½CV²', explanation:'Standard formula.',
        hasFormula:true, formula:'E = ½CV²'},
    82:{section:'electrical', q:'The unit of magnetic field strength is', answer:'(A) Tesla', explanation:'Standard unit.',
        hasFormula:false, formula:''},
    83:{section:'electrical', q:'Faraday\\\'s law of electromagnetic induction states that the induced EMF is proportional to the rate of change of', answer:'(D) Magnetic flux', explanation:'EMF = -dΦ/dt.',
        hasFormula:true, formula:'EMF = -d\\Phi/dt'},
    84:{section:'electrical', q:'The frequency of AC supply in India is', answer:'(B) 50 Hz', explanation:'Standard value.',
        hasFormula:false, formula:''},
    85:{section:'electrical', q:'The phase difference between voltage and current in a purely resistive AC circuit is', answer:'(A) 0°', explanation:'In phase.',
        hasFormula:false, formula:''},
    86:{section:'electrical', q:'The power factor of a purely inductive circuit is', answer:'(C) 0', explanation:'Phase difference is 90°. cos(90°) = 0.',
        hasFormula:true, formula:'PF = cos\\phi'},
    87:{section:'electrical', q:'The efficiency of a transformer is maximum when', answer:'(D) Copper loss = Iron loss', explanation:'Condition for maximum efficiency.',
        hasFormula:false, formula:''},
    88:{section:'electrical', q:'The slip of an induction motor is given by', answer:'(B) (N_s - N)/N_s', explanation:'Definition of slip.',
        hasFormula:true, formula:'s = (N_s - N)/N_s'},
    89:{section:'electrical', q:'The synchronous speed of a 4-pole, 50 Hz alternator is', answer:'(A) 1500 rpm', explanation:'N_s = (120f)/P = (120×50)/4 = 1500 rpm.',
        hasFormula:true, formula:'N_s = 120f/P'},
    90:{section:'electrical', q:'The unit of luminous flux is', answer:'(C) Lumen', explanation:'Standard unit.',
        hasFormula:false, formula:''},
    91:{section:'electrical', q:'The material used for the filament of an incandescent lamp is', answer:'(D) Tungsten', explanation:'Standard material.',
        hasFormula:false, formula:''},
    92:{section:'electrical', q:'The color code for a 100 Ω resistor with 5% tolerance is', answer:'(B) Brown, Black, Brown, Gold', explanation:'1 (Brown), 0 (Black), 10¹ (Brown), 5% (Gold).',
        hasFormula:false, formula:''},
    93:{section:'electrical', q:'The ripple factor of a half-wave rectifier is approximately', answer:'(A) 1.21', explanation:'Standard value.',
        hasFormula:false, formula:''},
    94:{section:'electrical', q:'The gain of a common-emitter amplifier is', answer:'(C) High', explanation:'Standard characteristic.',
        hasFormula:false, formula:''},
    95:{section:'electrical', q:'The number of flip-flops required to construct a mod-10 counter is', answer:'(D) 4', explanation:'2⁴ = 16. Need 4 flip-flops.',
        hasFormula:true, formula:'2ⁿ ≥ N'},
    96:{section:'electrical', q:'The output of an OR gate is 1 when', answer:'(A) At least one input is 1', explanation:'Definition of OR gate.',
        hasFormula:false, formula:''},
    97:{section:'electrical', q:'The Boolean expression for a 2-input XOR gate is', answer:'(B) A\'B + AB\'', explanation:'Standard expression.',
        hasFormula:false, formula:''},
    98:{section:'electrical', q:'The full form of LED is', answer:'(C) Light Emitting Diode', explanation:'Standard abbreviation.',
        hasFormula:false, formula:''},
    99:{section:'electrical', q:'The device used to convert AC to DC is', answer:'(A) Rectifier', explanation:'Standard function.',
        hasFormula:false, formula:''},
    100:{section:'electrical', q:'The unit of frequency is', answer:'(D) Hertz', explanation:'Standard unit.',
        hasFormula:false, formula:''},
  };
